import Head from "next/head";
import SettingHeader from "../components/SettingHeader";
import dynamic from "next/dynamic";
import { useEffect } from "react";

const Words = dynamic(() => import("../components/Words"), {
  ssr: false,
});

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SettingHeader />
      <Words />
    </div>
  );
}
